version: '3.8'

services:

  db:
    image: postgres:15-alpine  
    container_name: codex_db  
    restart: always
    
   
    environment:
      - POSTGRES_USER=codex
      - POSTGRES_PASSWORD=codex_password
      - POSTGRES_DB=codex_db
      
    
    ports:
      - '5432:5432'
      
   
    volumes:
      - ./data/postgres:/var/lib/postgresql/data