
version: '3.8'

services:
  
  db:
    image: postgres:15-alpine
    container_name: codex_db
    restart: always
    environment:
      - POSTGRES_USER=codex
      - POSTGRES_PASSWORD=codex_password
      - POSTGRES_DB=codex_db
    ports:
      - '5433:5432'
    volumes:
      - ./data/postgres:/var/lib/postgresql/data

  
  api:
    container_name: codex_api
    build: .
    ports:
      - '3000:3000'
    depends_on:
      - db
    volumes:
      - ./src:/app/src
    env_file:
      - ./.env
    environment:
      - DATABASE_URL=${DATABASE_URL}